### ISSUE TITLE
Please fix this help me, when I install code HungerGames it be close like this is there way of this page

### ISSUE THREAD

**Issue by NguyenQuangLap** [keithkfng/HungerGames#1]
PocketMine-MP Crash Dump Wed Dec 16 22:22:11 AKST 2015

Error: syntax error, unexpected ')'
File: /HungerGames/src/HG/Main
Line: 644
Type: E_PARSE

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[635] 				break;
[636] 			case 120:
[637] 				$this->sendToAll(TextFormat::YELLOW."The match will start in 2:00.");
[638] 				break;
[639] 			case 150:
[640] 				$this->sendToAll(TextFormat::YELLOW."The match will start in 2:30.");
[641] 				break;
[642] 			case 0:
[643] 				$this->gameStatus=2;
[644] 				$this->sendToAll(TextFormat::YELLOW."The match has started. Good luck!".);
[645] 				$this->sendToAll(TextFormat::RED."Warning!".TextFormat::YELLOW."There is no grace period!");
[646] 				$this->sendTip(TextFormat::GREEN."The match has started.")
[647] 				$this->lastTime=$this->godTime;
[648] 				$this->resetChest();
[649] 				foreach($this->players as $key=>$val)
[650] 				{
[651] 					$p=$this->getServer()->getPlayer($val["id"]);
[652] 					$p->setMaxHealth(25);
[653] 					$p->setHealth(25);
[654] 					$p->setLevel($this->level);

Backtrace:
#0 /src/pocketmine/Server(0): pocketmine\Server->crashDump(boolean)
#1 /DevTools_v1.10.0.phar/src/FolderPluginLoader/FolderPluginLoader(64): BaseClassLoader->loadClass(boolean)
#2 /DevTools_v1.10.0.phar/src/FolderPluginLoader/FolderPluginLoader(64): spl_autoload_call(boolean)
#3 /DevTools_v1.10.0.phar/src/FolderPluginLoader/FolderPluginLoader(64): class_exists(boolean)
#4 /src/pocketmine/plugin/PluginManager(152): FolderPluginLoader\FolderPluginLoader->loadPlugin(boolean)
#5 /src/pocketmine/plugin/PluginManager(296): pocketmine\plugin\PluginManager->loadPlugin(boolean)
#6 /DevTools_v1.10.0.phar/src/DevTools/DevTools(45): pocketmine\plugin\PluginManager->loadPlugins(boolean)
#7 /src/pocketmine/plugin/PluginBase(86): DevTools\DevTools->onEnable(boolean)
#8 /src/pocketmine/plugin/PharPluginLoader(123): pocketmine\plugin\PluginBase->setEnabled(boolean)
#9 /src/pocketmine/plugin/PluginManager(562): pocketmine\plugin\PharPluginLoader->enablePlugin(boolean)
#10 /src/pocketmine/Server(1896): pocketmine\plugin\PluginManager->enablePlugin(boolean)
#11 /src/pocketmine/Server(1882): pocketmine\Server->enablePlugin(boolean)
#12 /src/pocketmine/Server(1638): pocketmine\Server->enablePlugins(boolean)
#13 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct(boolean)
#14 (1): (boolean)
#15 (0): {main}(boolean)

PocketMine-MP version: 1.6dev #0 [Protocol 38; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT WINDOWS2012-001 6.3 build 9200 (Windows Server 2012 R2 Standard Edition) i586
PHP Version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
AdvancedKits 4.0.1 by luca28pet for API(s) 1.12.0
Alias 1.2.0 by ZacHack for API(s) 1.12.0
BanItem 2.1 by LDX for API(s) 1.0.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
CombatLogger 1.2.0 by Lambo for API(s) 1.12.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAuction 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyPShop 2.0.2 by onebone for API(s) 1.12.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
EconomyUsury 1.0.1 by onebone for API(s) 1.12.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
ItemCloud 1.3 by onebone for API(s) 1.4.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
NetherChests 1.1.1 by aliuly for API(s) 1.12.0
PocketMoney 4.0.1 by MinecrafterJPN, MinecrafterJPN for API(s) 1.10.0
PrizeWin 1.0.6 by LilCrispy2o9/Angelo Vidrio for API(s) 1.10.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
RandomItem 4.2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVPAlz2zaXfwVVOlNnRwepy7Y67o5rO8fWTrSW8/nbVh0PRIISa5JgCdCy2ul/3/cAkAQpOz63
nU2bCfkAvPsCSOrPlgxj1pq4w5EzGIz3B267xbKMZ63Jny25SWGodXI1PTyfnbTarZgJQZcIE5tE
0luiprZJnrDblHmS+eS7t9/BxCCMcFbvQ54sWfaewsKeyLzeh/e9MxomMCMKE5gxHg7/arfSKF8C
cCKznLVbHvcZUh8PRoBiLvV/i4zR6+9h4XgwLsEeFYy4fWei4LvW9G/lKhSdHwRL/At+GEU7F+xW
vuNZTOVk8j8np6efL7vz1sWKEYB4K7IOo4gISTNJwoT0J44Dw281vb272dhvsDHSbAydV2RjULEx
dO9kY9ivs2GYGGwzsQQrzCSVuTjo66XDF3C6okIzyvwuec+5T6Lcu/5m3uoadkePRX5+cgyYL2mW
hMkSEdxHOWMkFCThZJlRj5GUZSH3vyn1M76HYJjWyL0/Pzn5dK8ogE0hu8OXIirkBQTLQaFP7uOt
Jr63PT9jgsmjFRNyx3C4b00KOJjQW+2YyWlENywTBFj59pptDn749oZGipWR7U9/KojtCUAuLTli
csayG5btvFU3U4V0B1H9Mm+F/rz1q+Zk1G9gQFXJM3r7gdFIrnb6IzNvcNe85qThXZNO2Q2LCuki
vIHZEOsSbdea/NJ64xCVElLuXTMZQzroGeadtxNSQedzDe784GVUrI7zON1ZcB4xmqB+3rikd8xu
LgAirm7crut0nW66oplC/o5HPsumKr+ccgrXd4B2xkOg+CNEzxHYWGggMA3/KkCNXP+VyIk0uqK5
5EjlyqMQEzaVwStR8ZD/K3YbClkXY7ilfJ2EexrHGU0gz2c77qgPWLaxz+fbMK0xDanRGj2OVn9/
3DC8njaf1+bdS2b8NZ0VI+XFznD0VGp1De5+XSp0p509lKigOJ8XV50feHKS0EXEahj37sUIUtRs
6/YHX2Ueiaso1FT8Gpn9x5ljNO7fR6PBTucHpsjcYRP33iB39x5r7vuRu/cj3+vfk0Tux9a/Fxu0
AI/AVncPd7CFbqouz+ByZ6ii8y6MV1ceTwR0Qp6s4xuSHRfW1IEjorLlnzE0VX9VQ7+2W0uWsIxG
2EgBXhFy6K9abnfssxtYucjDyG9NHOi9Mi65x2HiYK/dommoprmDrgPTlqGEW+eRf2BBRq+jcIFr
ursKQ55QbC9bl2Hi87Ugny7I5cdPx58vZ33H7XccxyXj7oAofsh+33HITjFVa4TgPHLeJ9C6JD7N
fHLihxLEeUvC0d4YSKSrFAiMuuMu3v0BJR9u+3Dr6MErLpCBj58+XQBA3ayh2yz7ToE6OvRvaOIx
/6dQqnvDdg3ctjQ5hOTiAgRS+IpnAgsa9D+0v5cyiepXivwFNdkHPgCgPQVYC2gkoMv1WQqc4kIY
FDyQxzYA7dkgP58XnTMEHYxNP88uLj+fnx4DaM0WIpTI8ErKVEx6PbDcKl90PR73Sr56NWlA/sMo
pDVp1X275jB9pUZLzJ+p94F6168oJFLV0qly+4CISR5FwPuPNPkoWWxxX0Bs/vtNI50e/7vGufMC
xgHXfG6oPso6hvUjCNLslC6XFvMVrK5+t6n+UwaR7X8Ozo6mJ68mSUl9Ptcp/RluZjPWq8RBeXm8
oPKULyGd2yLb4Aec7pTGC/56LqfQzec2B08yYC4kjw8jltWSRQ1cF2hcF+fkhkcz4O3rEunt8OMM
aJEGueqMGIlmF4fnF1+mW3YEM67X6y4DnhB9V16j0YpexZKvBDVc1Glaqyp05ILRuCblACLymUJu
N1IPC9dw0oqzshFEYU+g5vJ4czj9aIlrAespxenu1+XlCVvA361wbJcBXLg0/uuqfwfmfmDuh+Z+
2NDPU9za8DGfM806MDOf18R4hHMX86EBUQJv6cMMNHXS/wd1YtvqKfrRolQ6KkV7vJ6msxVPt7Wk
wc/Q0YvyWlPAVAAXpXgFT48XbsaiaFs2BW2Ktvsaoj3TjgIYKqU03D1ByDsNeKf9/lEhbVM+2ZJf
RJ5ttqXU4Ho+32ps/1Yxc+SolLPg7zGCCsESGQIb0BhZgtrgZm81uKu3ErqH2S5dLwpNm4/X6rJq
soEK3lGVv8Q045YGbGhdAYNmQrpgEo9Z/avXk9uiPp+bm8d3WiEsk8yT3G4cLaAtD1QN+vVmf/+l
zX5F+dm7McDTUcazpABBcQ9xRAWr+a4FbIboXl1SGoV5tKlbray2gxeIrRGD5MAKPl9I2VMaZSVA
xHO/KZSCNZzx4aQzfI3SqCRB+o/fchZtssHRjYsjM9H7T31xUGJFY57RZHPJs8i3u2cL2Cwrg8cZ
86U2jIGDteLgKTY8m6V0ndQkMZC6/UaP2eK4LxDDkG3y/rXO/459zSeV4tRjGVumGrhZJtyH7dN/
BfskzEP6z04tNGK/0cTPOOCzzh07ha/KjLFeTIVkWa8mL6jFbIzAu+0uwYY+cPqFeyovowEg/6/p
JxhrAF7Nmy2e5vM6g09VWJ3Fno0MVZKFf7DL0N4ClaBmOm7s70/D6CgLRbrp8/3eYbJkESf/Cv0s
5K+oB8PLU2J5mmdsyrLY9vwK1jyDaTQH4+G7d47zem5/pRGCEQsOrMun7+xxpXH0CgvIfA4hwePG
WaEFtKQedvsPHhbetX8dlPvUF/YXFVtPser59BC6wMaBogW07TrN2LswodGV+9DJ6N4LhJmxbMk2
V8cskxQcdGadL1bXKKB+itiEftX4RuhZGKcROwT+LaEtYN2Zd5vSNo+oQJYVX65CL309B6+4AQFt
zp59ZmVhARVc0PSCH9utfgGpNxhbh+DvaHT9amfHkqaS+9DcV8Qf4bP45sQRj6El8WuHwnW4Jcc/
HJk1vp4SnP+CJv+crWlm98AW0Bax6z5byBcJV7HzFMlUM4sP4w4zaclWAzfrpHO1YJJe+ezm6o0z
bGxipidnND3jPlr+tbwzZTFNY4VzPlfNLwPWaAZdVoPRpzYPFre9WUyjqPPzUWd6R6tVo1PozWz+
mnorwM0Adp6w3XuNVlRpKtXMPKXhfmY3WpPdOoMOs5TXnKsx0NxIDf/BgyuqeaoOk0seH9mYHa2o
bPRlCtQ8sxk83JY9uM2yur4tEWsHRve0a8hYdfXiZk0hqRX1DyxKa4Vha+gB2z9rk2Y3EI+IkpXi
5G/Zr22JD9p6n9HFj9Ru+gpIXTeDJ6UP9/l5BDxHyIuMJiLQKbyhryWwt6DLv0VhhSpATz+FUXRO
JbMUVYIaLwv832z1G/voMypEeMNMnmi1608a30NLPJPYGMBu4PpLeocer4H7DLj/WxRZqqqMz0ua
pVuRqYBNbTrbfWeYXYsX67PmZ8BWxNfWbe1YvNJeYKjP50JxDP1OWjTmhvtHZOp34e3Z5ke+tg/Y
C5Alfr2TO8JDhjBZkjOahPTVzjQLwo/v2vClJ5oB22DZArl6zaoLxR7SigwZvh/1ZlrekSOeBOGS
4Bv982yevLlkPjlmHnHHpN+f9N3JYEgOf5pd4ItaI5wRc+kfzHPHobve0Tx3me+SCO8ZTUiiLhxO
9ITF0QovAuqRmG5IjNNpkJBvEJHmrINV9MDdd8f7CjuLebbpRGEcyoOOi6D1CgQEiJAHPAgQQpOE
54mHDo1vQHeotwrZDYvBLcQBTxRyPEzsmBYHTHbgKOz01qwRB0MlDTR2fN0JonC5KtHrtWBKaPvq
+GK+EAd4iy/bQ9vJNNqAZ8BMCTNoVtBwezwr79Ob1CDzwyAIvTySmwMloX6ZT/KsI5hER9JE1GvV
HfTCA/2hRQUUjPnWHPyS4+Dd6eEFgrSvdX7PWbYxBA0og0RUcIPX3RRSFfSC/sF/qD+gjlzyjqA3
zCzEV+zK/NHdxBF6D0F3JJ5ynBz4BvUq/yGgB1JtZztnU+VR5GLFBCOFaIRmjMgVI5AuBVxQSTw0
qCQLRsLEi3Lo4fHziC3P1dhmPIa1AaJoYhU0YG3C8ehTIFKivqMgG55nBhsJAwI2CoNQ0QDzZOAf
kHQV6k9sXSLs+SygYCJB1jz5ThKapoxmBBUUg8j4SvcGRCD4BryWfr1iCclTqII+IOgiSu3mGuEE
b8ibixUk304EQOAmoskyp0tG8KMYpT4TFCKE+4gDlfAPpWC9+GjFPCNPfSkwUtQBlnTX4XWYwkaI
dnm27OFd7xTC54oHVx9nn6/Gg/1O/wrXKZWWqCZkDolqOW9pYpcrdYhMJCf4oQWh6tuVTGlbYjqO
KH4RpIaVbhW/wAtcMalMDBvB0GNkBcUoUkaPFWodLxVZlRTViFjl0ucYafpTJGTJvCjqRVwwv2Du
EOOWYFLAvGsKG7kJKflv9Hs1SUVAUfQmBF9F0otnK1hL0YMFB74MLW1AapCRXIB7Qp4GB1FyQvmG
mZDzfa21aqgD7C2AOZuEfjO7wAXyE0wFBJwZfAVZXmyI8TC1wERoOW4r5c0lfjbEE3A46vskY0L7
JbILnngNbFEBbTbmP/yEZsFQN2AG9ntOIzTQEvqRhNzQKGdkx5CFhP5Wodc0ITswTMUdsDC+MDeB
cU39Ux4vQP8Qcodik3gXVFxDTGTXEGRdPeMLGEZ5byEuzltl0PXk4CowX7SJ2nISk+nAodugkBg0
KLCgKgVBKUNYnCcQXTjFYJ8pZwK5IAQzfgtZWTJQBYilAiEp2UMNFyx9DDCScRJGbJuE8jvQoczU
Op9hVVAe2lhNdkAKsDzpa90oSTpG2onCVcS1rlQmqt9HfAGqxkpO9ABRJQzzWMyWdLGRwBqZaZYc
xUQo0ORFVgD51NdhRv0Ey5IphgYklJaCENwIUhvk/UQhCyCfFDS1S4BYuXLoJQeJOAYP6k9RWipG
dX2dEKcQhrxROV1CcqL+/wMxsEN6QAgsvy8UQkieKj5Mgiv5MvgEgbDDGgp5qeQK6RasuU5/WHE3
VV+0IRsYtQIJeyqhGy7LyHSBICQnX/ugmtPBDUERk6YYcOiCE4ho0CVmlPtUrVUMXVSk6gTmBj1N
Y9dYIFKryC/SmKbzGRMP1k21qLu9ABVhGlxQa8o8LK9CKQq51nrXa0tRQLcsFZXIA8fILN7ew5bR
wKDSwJJmsN1kHY9Hke7ydDTeqWnlcMiSWUXMKoj3mCa5Kuc2N9Dw5OAnb9tFHtlyFOMpOi8HQZFR
4soHu+SzrqDqDrxlxfPIL1kJIe+sE1Kxr33bfPkIoo4dp5KWvHmnYmYrtyo/0jhK4YKMx0WS1qvN
jI6d0RqWBoGMQbfd5A7vaqzG3tpb5cm1KKxwqqIEU6sCI5+4g0H5iO7C2yqsM2h2hJ7UwU4Du6cK
m0ZWOIEJrP2xxfUx14ubpsXCgh2aXlrHo6mZia+qB1XoOh7Fh/1GE8ZrCqI4ZPUKD6LEvwmTaDOr
iQRninTVXeBnrqoNoth7Q7EFDzRZTgWvbpXNqE5tC1bWX5O83tgJsRjD5JFtJGJvk45rhYCus4p0
RxbsQIIajYvsVFV3tUnBsurrFGqMrFcD0HDWJR9gGwZqP4AeHVz9aPqlDWuBiwXksXXoy5WuCCZD
lAQ6isCE7JbtSNWqCKUia3KXHPoQiysaBfjGj+6gfAb+aIgBWe2nPLGD2eoHLGy1Pu3kFkMX2zAa
tXViQOLmi6cuAbdiKgyww/gyTaZFf1LtKLAFw0XqaQ0izdMk7RhAvS9UO0m2yJeTsuX5gbjY6pjq
hV2umlB0uEJlxBUrOl/d/WvduXbfKkhPqE/J26S39Ap149Mx0WCg2I429jisaG5RFpBO7/PUZOOA
qALlDB4oVxofNIs6etGExDC4LHc/IKD6nADZv8GPH3SaozUa6hPyYvehWQAly22OVGwbs7759Pni
ZEJUPof/vRy2hQlsCxUqdYKERjVMGuolk5YDHNZs6cG+B7KRkVr5mSp9wA/6lUTf6jumRGFS1BVQ
OxpuxHHElL0yW9QHinxY9OozDHAUdoE/FlCR3HEhqO6g1SZ9GHDvGmDS6741QS6YzYtxlQvEjpvC
4uN2/OBd08SWQ1tXbcarXTomD7Vzw05OpxAarelGaPwGU8PHapXBuNhhzPPELi7C9JEFMygK4tRb
HMj4eDMhw68tpxlAfS2HxtOsbMTd79+DQXlfwvSOeME0xgXDHwIg6vQIMx6axsKsT5Ws9Flkzxm9
gVKPfWeIRwAMt4/pxhx7mGpXtlUqyQTqOLdIrWUiDPJITeQC3LmDQR16ukSpDWSGpwzgMoC4UNxv
HHdwOoIEjdGLYpNxsXCVmrjDRKjiykRn9JbQppZgB+epmlN5S9NCxpXPqR/mwlpqrEMNpyqsi+XG
O3EF9E06r+GRXidPffBZm13i4bso2t/w/KBea7Ug1Ta1kqW7LYzJpmsaqlOI33OWM2N9g8GkDDXS
EWDICdl7JsaUp3lUYjR3WPy2kONfFc8d0KoWQB9mdpS/CdSxVnKM3yLjcZOBu2WKwTPACSka0ML0
+PlxnkL7VfWl2oVVGiraHYMV8O3q1YY8EhhpwJoi2RJsoDRehBA1xTR1PovpTp9MTIoUh4cp+FsR
RMN1hTeOVfi+2Y9YiRMjo4OHXk1YWbwa8HSVhknAbddZcfQXRbxrnYtCc1bym/BkE+O2RcWaADsI
i3HckZkJpJqgBAA/pYQul1DxzAFJeRCFPS3+sMb1/dJpzhCluI8z1KQOB+MU21jAm/SMSWGmLOmY
ZsHuWBWcp7VDtSM8b1VHfiziKdbLNsG3QfAgCvgqW0bonALo+RkYA+pjgr0HTitLfI42hCi3EBHz
3MXqbXJok4XUJbZIrAaftqCeUNAQW6rCd4fvURR+sFz07tDTUaz/xS02VUDLMDQpODODEDR4ZjAh
v+BlB0pdWx0i/Frg1pm3apPsE2wlWLEf0lvV4rmA2oPedSSuNviqogrVzaAqYmhyQmDZNB41MQxl
xYa5JvgsAVOCKY0V1QnBRwqT/ve77dH+rdse3A7a/e/d733oEHR23MEniR7msIM9B3+3Rwh9Nxy9
NY8P2K1kCapIvZR6BNXQ+pp/4UG3tCqfiuHxMf4IQAXQP1FVPDRTD3nLxVC8luVYEEYSXyhoOcUj
7kCm5egKAla/ogQDITZw5dBvonwhFh8OQ8e5SWU5OpueKpz4riz3F16JJPWyirFzFpj9Jox/+xG0
yYJgb+F749HCWTAa7AVD6rNx4IyDveEeG/vDgR/4e/0x+RZfTdRbiRKdMD+FYMkab8TvkfrlA3NF
RviOttuBKCEd9SMKzsgZwKUiP/DGe3uL8WLhDRx/MKbBgHqDYeD7w8XuYrTY3dsN2Aj+KPKSX7ME
qofRHv7IQpjqV+P76rWLP/RvPujXlOD6Fh8DFTbhMQ45zsB1+/jd7PT4s3kZbKh/iwJ/TsT6PlI/
kP332WlJbe37tyU+Gzdc48bLYgwg6yyUFuSS0WtIKNpISlXQvFcolLbCcjbeSDbQP2DR0fwJlQRE
tWShH3KUgA1Vj72KLwVSc5pjZHJRKbA5uvK5hCRSkoq1zxkcP2PR+jxVZRSm7KJ6kP47/PTnVm3S
zKtg49Zff/0vyS8yRw==
===END CRASH DUMP===

**Comment by keithkfng** [comment]
Will look into this issue.

**Comment by keithkfng** [comment]
Try it now. It should be fixed.

**Comment by EpicArtz08999** [comment]
nope

Parse error: syntax error, unexpected '$this' (T_VARIABLE) in C:\Users\Blenda\Downloads\PocketMine-MP\plugins\HungerGames\src\HG\Main.php on line 647

Call Stack:
    0.0281     447520   1. {main}() C:\Users\Blenda\Downloads\PocketMine-MP\PocketMine-MP.phar:0
    0.0312     442424   2. require('phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php') C:\Users\Blenda\Downloads\PocketMine-MP\PocketMine-MP.phar:1
    1.9938     582984   3. pocketmine\Server->__construct() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php:466
    4.3936   16676952   4. pocketmine\Server->enablePlugins() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:1637
    4.3936   16677008   5. pocketmine\Server->enablePlugin() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:1881
    4.3936   16677104   6. pocketmine\plugin\PluginManager->enablePlugin() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:1895
    4.3944   16678768   7. pocketmine\plugin\PharPluginLoader->enablePlugin() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:562
    4.3950   16678832   8. pocketmine\plugin\PluginBase->setEnabled() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PharPluginLoader.php:123
    4.3950   16678912   9. DevTools\DevTools->onEnable() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginBase.php:86
    4.3965   16682328  10. pocketmine\plugin\PluginManager->loadPlugins() phar://C:/Users/Blenda/Downloads/PocketMine-MP/plugins/DevTools_v1.10.0.phar/src/DevTools/DevTools.php:45
    4.4074   16684584  11. pocketmine\plugin\PluginManager->loadPlugin() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:296
    4.4083   16690112  12. FolderPluginLoader\FolderPluginLoader->loadPlugin() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:152
    4.4097   16695552  13. class_exists() phar://C:/Users/Blenda/Downloads/PocketMine-MP/plugins/DevTools_v1.10.0.phar/src/FolderPluginLoader/FolderPluginLoader.php:64
    4.4097   16695704  14. spl_autoload_call() phar://C:/Users/Blenda/Downloads/PocketMine-MP/plugins/DevTools_v1.10.0.phar/src/FolderPluginLoader/FolderPluginLoader.php:64
    4.4097   16695720  15. BaseClassLoader->loadClass() phar://C:/Users/Blenda/Downloads/PocketMine-MP/plugins/DevTools_v1.10.0.phar/src/FolderPluginLoader/FolderPluginLoader.php:64

**Comment by keithkfng** [comment]
OMG it's not the same error... Will you post it in another issue?
